name: Release

on:
  push:
    branches:
      - main

<<<<<<< HEAD
permissions:
  contents: write
  issues: write
  pull-requests: write

=======
>>>>>>> 889611d (Feat/#12 자동 릴리즈 파이프라인 구축 (#13))
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
<<<<<<< HEAD
          node-version: 20.9.0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
=======
          node-version: 18

      - name: Install dependencies
        run: npm ci
>>>>>>> 889611d (Feat/#12 자동 릴리즈 파이프라인 구축 (#13))

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
